// VIEW PROJECTS

export const VIEW_PROJECTS_ROWS_DATA = [
  {
    id: '101',
    projectCode: 'DMS',
    projectName: 'DMS',
    title: 'DMS Title',
    projectDescription: '<ol><li>Document Management System </li></ol>',
    projectLead: 'Shuaib (Project Lead)',
    version: '2.0.1',
    action: 'Active',
    role: 'Developer',
    documentCategory: 'Client',
  },
  {
    id: '201',
    projectCode: 'TG_01',
    projectName: 'Tech Guard',
    projectId: '1125',
    title: 'Title 1',
    projectDescription: 'TechGuard: Fortifying Digital Frontiers for Secure Connectivity',
    projectLead: 'Rajshekar (Project Lead)',
    version: '2.0.1',
    action: 'Active',
    role: 'Developer',
    documentCategory: 'Client',
  },
  {
    id: '301',
    projectCode: 'DEMO',
    projectName: 'Demo Project',
    title: 'Demo Project',
    projectDescription: 'Demo Project',
    projectLead: 'Shuaib (Project Lead)',
    version: '2.0.1',
    action: 'Active',
    role: 'Developer',
    documentCategory: 'Server',
  },
  {
    id: '401',
    projectCode: 'GHDA',
    projectName: 'Global Health Data Analytics',
    title: 'Global Health Data Analytics',
    projectDescription:
      '<p class="ql-align-center"><em>The "Global Health Data Analytics Platform for Pandemic Preparedness and Response" project is a ground breaking initiative designed to create a robust and scalable data analytics platform to enhance global health monitoring, prediction, and response capabilities. Leveraging advanced analytics, artificial intelligence, and real-time data streams, the platform aims to provide actionable insights for early detection, rapid response coordination, and effective resource allocation during pandemics.</em></p>',
    projectLead: 'Vinay (Project Lead)',
    version: '2.0.1',
    action: 'Active',
    role: 'Team Lead',
    documentCategory: 'Server',
  },
  {
    id: '211',
    projectCode: 'DSK',
    projectName: 'DeskTime',
    title: 'DeskTime',
    projectDescription: 'desk time',
    projectLead: 'Praveen (Project Lead)',
    version: '2.0.1',
    action: 'Active',
    role: 'Product Manager',
    documentCategory: 'Database',
  },
  {
    id: '516',
    projectCode: 'ITC',
    projectName: 'ITC01 ',
    projectId: '1129',
    title: 'ITC01',
    projectDescription:
      'ITC-  Project Lead is Gurupadayya Project Lead is Gurupadayya Project Lead is Gurupadayya Project Lead is Gurupadayya',
    projectLead: 'Himam (Project Lead)',
    version: '1.0.1',
    action: 'Active',
    role: 'Product manager',
    documentCategory: 'Server',
  },
  {
    id: '812',
    projectCode: 'TG_05',
    projectName: 'Tech Guard',
    projectId: '1125',
    title: 'Tech Guard Title 2',
    projectDescription: 'TechGuard: Testing tech guard',
    projectLead: 'Neeranjan (Project Lead)',
    version: '2.0.2',
    action: 'Active',
    role: 'Team Lead',
    documentCategory: 'Server',
  },
  {
    id: '813',
    projectCode: 'TG_05',
    projectName: 'Tech Guard',
    projectId: '1125',
    title: 'Tech Guard Title 2',
    projectDescription: 'TechGuard: Testing tech guard',
    projectLead: 'Neeranjan (Project Lead)',
    version: '2.0.3',
    action: 'Active',
    role: 'Team Lead',
    documentCategory: 'Server',
  },
  {
    id: '814',
    projectCode: 'TG_05',
    projectName: 'Tech Guard',
    projectId: '1125',
    title: 'Tech Guard Title 2',
    projectDescription: 'TechGuard: Testing tech guard',
    projectLead: 'Neeranjan (Project Lead)',
    version: '2.0.4',
    action: 'Active',
    role: 'Team Lead',
    documentCategory: 'Server',
  },

  // 3rd
  {
    id: '901',
    projectCode: 'TG_81',
    projectName: 'Tech Guard',
    projectId: '1125',
    title: 'Tech Guard Title 6',
    projectDescription: 'TechGuard: Testing',
    projectLead: 'Praveen (Project Lead)',
    version: '2.1.1',
    action: 'Active',
    role: 'Team Lead',
    documentCategory: 'Database',
  },
  {
    id: '902',
    projectCode: 'TG_81',
    projectName: 'Tech Guard',
    projectId: '1125',
    title: 'Tech Guard Title 6',
    projectDescription: 'TechGuard: Testing',
    projectLead: 'Himam (Project Lead)',
    version: '2.0.9',
    action: 'Active',
    role: 'Team Lead',
    documentCategory: 'Database',
  },
  {
    id: '903',
    projectCode: 'TG_81',
    projectName: 'Tech Guard',
    projectId: '1125',
    title: 'Tech Guard Title 6',
    projectDescription: 'TechGuard: Testing',
    projectLead: 'Neeranjan (Project Lead)',
    version: '2.0.4',
    action: 'Active',
    role: 'Team Lead',
    documentCategory: 'Database',
  },
];

export const VIEW_PROJECTS_COLUMNS_DATA = [
  { field: 'projectCode', headerName: 'Project Code', hide: true, width: 150 },
  { field: 'projectName', headerName: 'Project Name', width: 200 },
  { field: 'projectDescription', headerName: 'Project Description', width: 400 },
  { field: 'projectLead', headerName: 'Project Lead', width: 200 },
  { field: 'col6', headerName: 'Action', width: 200 },
];

// CREATE PROJECT

export const LEAD_OPTIONS = [
  { value: 'Shuaib (Project Lead)', label: 'Shuaib (Project Lead)' },
  { value: 'Test Manager (Project Lead)', label: 'Test Manager (Project Lead)' },
  { value: 'Rajshekar (Project Lead)', label: 'Rajshekar (Project Lead)' },
  { value: 'Vinay (Project Lead)', label: 'Vinay (Project Lead)' },
  { value: 'Praveen (Project Lead)', label: 'Praveen (Project Lead)' },
  { value: 'Himam (Project Lead)', label: 'Himam (Project Lead)' },
  { value: 'Neeranjan (Project Lead)', label: 'Neeranjan (Project Lead)' },
];
export const INVITE_OPTIONS = [
  { value: 'Shuaib (Project Lead)', label: 'Shuaib (Project Lead)' },
  { value: 'Test Manager (Project Lead)', label: 'Test Manager (Project Lead)' },
  { value: 'Rajshekar (Project Lead)', label: 'Rajshekar (Project Lead)' },
  { value: 'Vinay (Project Lead)', label: 'Vinay (Project Lead)' },
  { value: 'Praveen (Project Lead)', label: 'Praveen (Project Lead)' },
  { value: 'Himam (Project Lead)', label: 'Himam (Project Lead)' },
  { value: 'Neeranjan (Project Lead)', label: 'Neeranjan (Project Lead)' },
];



// DOCUMENTS
export const VIEW_DOCUMENTS_ROW_DATA = [
  {
    id: '101',
    projectCode: 'DMS',
    projectName: 'DMS',
    projectId: '1721',
    title: 'DMS Title',
    projectDescription: '<ol><li>Document Management System </li></ol>',
    projectLead: 'Shuaib (Project Lead)',
    version: "2.0.1",
    action: 'Active',
    role: 'Developer',
    documentCategory: 'Client',
  },
  {
    id: '201',
    projectCode: 'TG_01',
    projectName: 'Tech Guard',
    projectId: '1125',
    title: 'Title 1',
    projectDescription: 'TechGuard: Fortifying Digital Frontiers for Secure Connectivity',
    projectLead: 'Rajshekar (Project Lead)',
    version: '2.0.1',
    action: 'Active',
    role: 'Developer',
    documentCategory: 'Client',
  },

  // DESK TIME (1)
  {
    id: '201',
    projectCode: 'DSK',
    projectName: 'DeskTime',
    title: 'DeskTime',
    projectId: '1088',
    projectDescription: 'desk time',
    projectLead: 'Praveen (Project Lead)',
    version: '2.0.1',
    action: 'Active',
    role: 'Product Manager',
    documentCategory: 'Database',
  },
  {
    id: '202',
    projectCode: 'DSK',
    projectName: 'DeskTime',
    title: 'DeskTime',
    projectId: '1088',
    projectDescription: 'desk time',
    projectLead: 'Praveen (Project Lead)',
    version: '2.0.5',
    action: 'Active',
    role: 'Product Manager',
    documentCategory: 'Database',
  },

  // DESK TIME (2)
  {
    id: '221',
    projectCode: 'DSK_02',
    projectName: 'DeskTime',
    title: 'Desk Time Title 2',
    projectId: '1088',
    projectDescription: 'desk time',
    projectLead: 'Praveen (Project Lead)',
    version: '2.0.1',
    action: 'Active',
    role: 'Developer',
    documentCategory: 'Server',
  },
  {
    id: '222',
    projectCode: 'DSK_02',
    projectName: 'DeskTime',
    title: 'Desk Time Title 2',
    projectId: '1088',
    projectDescription: 'desk time',
    projectLead: 'Praveen (Project Lead)',
    version: '2.0.8',
    action: 'Active',
    role: 'Developer',
    documentCategory: 'Server',
  },
  {
    id: '223',
    projectCode: 'DSK_02',
    projectName: 'DeskTime',
    title: 'Desk Time Title 2',
    projectId: '1088',
    projectDescription: 'desk time',
    projectLead: 'Praveen (Project Lead)',
    version: '2.1.1',
    action: 'Active',
    role: 'Developer',
    documentCategory: 'Server',
  },

  {
    id: '516',
    projectCode: 'ITC',
    projectName: 'ITC01 ',
    projectId: '1129',
    title: 'ITC01',
    projectDescription:
      'ITC-  Project Lead is Gurupadayya Project Lead is Gurupadayya Project Lead is Gurupadayya Project Lead is Gurupadayya',
    projectLead: 'Himam (Project Lead)',
    version: '1.0.1',
    action: 'Active',
    role: 'Product manager',
    documentCategory: 'Server',
  },
  {
    id: '812',
    projectCode: 'TG_05',
    projectName: 'Tech Guard',
    projectId: '1125',
    title: 'Tech Guard Title 2',
    projectDescription: 'TechGuard: Testing tech guard',
    projectLead: 'Neeranjan (Project Lead)',
    version: '2.0.2',
    action: 'Active',
    role: 'Team Lead',
    documentCategory: 'Server',
  },
  {
    id: '813',
    projectCode: 'TG_05',
    projectName: 'Tech Guard',
    projectId: '1125',
    title: 'Tech Guard Title 2',
    projectDescription: 'TechGuard: Testing tech guard',
    projectLead: 'Neeranjan (Project Lead)',
    version: '2.0.3',
    action: 'Active',
    role: 'Team Lead',
    documentCategory: 'Server',
  },
  {
    id: '814',
    projectCode: 'TG_05',
    projectName: 'Tech Guard',
    projectId: '1125',
    title: 'Tech Guard Title 2',
    projectDescription: 'TechGuard: Testing tech guard',
    projectLead: 'Neeranjan (Project Lead)',
    version: '2.0.4',
    action: 'Active',
    role: 'Team Lead',
    documentCategory: 'Server',
  },

  // 3rd
  {
    id: '901',
    projectCode: 'TG_81',
    projectName: 'Tech Guard',
    projectId: '1125',
    title: 'Tech Guard Title 6',
    projectDescription: 'TechGuard: Testing',
    projectLead: 'Praveen (Project Lead)',
    version: '2.1.1',
    action: 'Active',
    role: 'Team Lead',
    documentCategory: 'Database',
  },
  {
    id: '902',
    projectCode: 'TG_81',
    projectName: 'Tech Guard',
    projectId: '1125',
    title: 'Tech Guard Title 6',
    projectDescription: 'TechGuard: Testing',
    projectLead: 'Himam (Project Lead)',
    version: '2.0.9',
    action: 'Active',
    role: 'Team Lead',
    documentCategory: 'Database',
  },
  {
    id: '903',
    projectCode: 'TG_81',
    projectName: 'Tech Guard',
    projectId: '1125',
    title: 'Tech Guard Title 6',
    projectDescription: 'TechGuard: Testing',
    projectLead: 'Neeranjan (Project Lead)',
    version: '2.0.4',
    action: 'Active',
    role: 'Team Lead',
    documentCategory: 'Database',
  },
];



/// UPDATED

export const VIEW_DOCUMENTS = [
  {
    id: '101',
    projectId: '1721',
    projectCode: 'DMS',
    projectName: 'DMS',
  
    projectDescription: '<ol><li>Document Management System </li></ol>',
    projectLead: 'Shuaib (Project Lead)',
    version: "2.0.1",
    role: 'Developer',
    documentCategory: 'Client',
  },
  {
    id: '201',
    projectCode: 'TG_01',
    projectName: 'Tech Guard',
    projectId: '1125',
    title: 'Title 1',
    projectDescription: 'TechGuard: Fortifying Digital Frontiers for Secure Connectivity',
    projectLead: 'Rajshekar (Project Lead)',
    version: '2.0.1',
    action: 'Active',
    role: 'Developer',
    documentCategory: 'Client',
  },

  // DESK TIME (1)
  {
    id: '201',
    projectCode: 'DSK',
    projectName: 'DeskTime',
    title: 'DeskTime',
    projectId: '1088',
    projectDescription: 'desk time',
    projectLead: 'Praveen (Project Lead)',
    version: '2.0.1',
    action: 'Active',
    role: 'Product Manager',
    documentCategory: 'Database',
  },
  {
    id: '202',
    projectCode: 'DSK',
    projectName: 'DeskTime',
    title: 'DeskTime',
    projectId: '1088',
    projectDescription: 'desk time',
    projectLead: 'Praveen (Project Lead)',
    version: '2.0.5',
    action: 'Active',
    role: 'Product Manager',
    documentCategory: 'Database',
  },

  // DESK TIME (2)
  {
    id: '221',
    projectCode: 'DSK_02',
    projectName: 'DeskTime',
    title: 'Desk Time Title 2',
    projectId: '1088',
    projectDescription: 'desk time',
    projectLead: 'Praveen (Project Lead)',
    version: '2.0.1',
    action: 'Active',
    role: 'Developer',
    documentCategory: 'Server',
  },
  {
    id: '222',
    projectCode: 'DSK_02',
    projectName: 'DeskTime',
    title: 'Desk Time Title 2',
    projectId: '1088',
    projectDescription: 'desk time',
    projectLead: 'Praveen (Project Lead)',
    version: '2.0.8',
    action: 'Active',
    role: 'Developer',
    documentCategory: 'Server',
  },
  {
    id: '223',
    projectCode: 'DSK_02',
    projectName: 'DeskTime',
    title: 'Desk Time Title 2',
    projectId: '1088',
    projectDescription: 'desk time',
    projectLead: 'Praveen (Project Lead)',
    version: '2.1.1',
    action: 'Active',
    role: 'Developer',
    documentCategory: 'Server',
  },

  {
    id: '516',
    projectCode: 'ITC',
    projectName: 'ITC01 ',
    projectId: '1129',
    title: 'ITC01',
    projectDescription:
      'ITC-  Project Lead is Gurupadayya Project Lead is Gurupadayya Project Lead is Gurupadayya Project Lead is Gurupadayya',
    projectLead: 'Himam (Project Lead)',
    version: '1.0.1',
    action: 'Active',
    role: 'Product manager',
    documentCategory: 'Server',
  },
  {
    id: '812',
    projectCode: 'TG_05',
    projectName: 'Tech Guard',
    projectId: '1125',
    title: 'Tech Guard Title 2',
    projectDescription: 'TechGuard: Testing tech guard',
    projectLead: 'Neeranjan (Project Lead)',
    version: '2.0.2',
    action: 'Active',
    role: 'Team Lead',
    documentCategory: 'Server',
  },
  {
    id: '813',
    projectCode: 'TG_05',
    projectName: 'Tech Guard',
    projectId: '1125',
    title: 'Tech Guard Title 2',
    projectDescription: 'TechGuard: Testing tech guard',
    projectLead: 'Neeranjan (Project Lead)',
    version: '2.0.3',
    action: 'Active',
    role: 'Team Lead',
    documentCategory: 'Server',
  },
  {
    id: '814',
    projectCode: 'TG_05',
    projectName: 'Tech Guard',
    projectId: '1125',
    title: 'Tech Guard Title 2',
    projectDescription: 'TechGuard: Testing tech guard',
    projectLead: 'Neeranjan (Project Lead)',
    version: '2.0.4',
    action: 'Active',
    role: 'Team Lead',
    documentCategory: 'Server',
  },

  // 3rd
  {
    id: '901',
    projectCode: 'TG_81',
    projectName: 'Tech Guard',
    projectId: '1125',
    title: 'Tech Guard Title 6',
    projectDescription: 'TechGuard: Testing',
    projectLead: 'Praveen (Project Lead)',
    version: '2.1.1',
    action: 'Active',
    role: 'Team Lead',
    documentCategory: 'Database',
  },
  {
    id: '902',
    projectCode: 'TG_81',
    projectName: 'Tech Guard',
    projectId: '1125',
    title: 'Tech Guard Title 6',
    projectDescription: 'TechGuard: Testing',
    projectLead: 'Himam (Project Lead)',
    version: '2.0.9',
    action: 'Active',
    role: 'Team Lead',
    documentCategory: 'Database',
  },
  {
    id: '903',
    projectCode: 'TG_81',
    projectName: 'Tech Guard',
    projectId: '1125',
    title: 'Tech Guard Title 6',
    projectDescription: 'TechGuard: Testing',
    projectLead: 'Neeranjan (Project Lead)',
    version: '2.0.4',
    action: 'Active',
    role: 'Team Lead',
    documentCategory: 'Database',
  },
];